package vistas;

import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import org.com.logica.controlador;

/**
 *
 * @author Jherson
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }

     public void mostrarVentanasInternas(JInternalFrame frame,String nombre){
        frame.setVisible(true);
        frame.setTitle(nombre);
        frame.setIconifiable(true);
        frame.setClosable(true);
        frame.setResizable(true);
        frame.setDefaultCloseOperation(JInternalFrame.DISPOSE_ON_CLOSE);
        frame.pack();

        jDesktopPane1.add(frame);
        frame.moveToFront();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_archivo = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        menu_salir = new javax.swing.JMenuItem();
        menu_usuario = new javax.swing.JMenu();
        menu_conf = new javax.swing.JMenuItem();
        menu_controller = new javax.swing.JMenuItem();
        menu_administrador = new javax.swing.JMenu();
        menu_user = new javax.swing.JMenuItem();
        menu_impresiones = new javax.swing.JMenuItem();
        menu_about = new javax.swing.JMenu();
        menu_acerca = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 339, Short.MAX_VALUE)
        );

        menu_archivo.setText("Archivo");
        menu_archivo.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N

        jMenuItem7.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/com/pictures/logout.png"))); // NOI18N
        jMenuItem7.setText("Cerrar Sesion");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        menu_archivo.add(jMenuItem7);

        menu_salir.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        menu_salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/com/pictures/salida.png"))); // NOI18N
        menu_salir.setText("Salir");
        menu_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_salirActionPerformed(evt);
            }
        });
        menu_archivo.add(menu_salir);

        jMenuBar1.add(menu_archivo);

        menu_usuario.setText("Usuario");
        menu_usuario.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N

        menu_conf.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        menu_conf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/com/pictures/controles.png"))); // NOI18N
        menu_conf.setText("Configuracion");
        menu_conf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_confActionPerformed(evt);
            }
        });
        menu_usuario.add(menu_conf);

        menu_controller.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        menu_controller.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/com/pictures/impresora.png"))); // NOI18N
        menu_controller.setText("Controlador");
        menu_controller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_controllerActionPerformed(evt);
            }
        });
        menu_usuario.add(menu_controller);

        jMenuBar1.add(menu_usuario);

        menu_administrador.setText("Administrador");
        menu_administrador.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N

        menu_user.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        menu_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/com/pictures/equipo.png"))); // NOI18N
        menu_user.setText("USUARIOS");
        menu_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_userActionPerformed(evt);
            }
        });
        menu_administrador.add(menu_user);

        menu_impresiones.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        menu_impresiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/com/pictures/reportar.png"))); // NOI18N
        menu_impresiones.setText("IMPRESIONES");
        menu_administrador.add(menu_impresiones);

        jMenuBar1.add(menu_administrador);

        menu_about.setText("About");
        menu_about.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N

        menu_acerca.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        menu_acerca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/org/com/pictures/pregunta.png"))); // NOI18N
        menu_acerca.setText("Acerca de");
        menu_acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_acercaActionPerformed(evt);
            }
        });
        menu_about.add(menu_acerca);

        jMenuBar1.add(menu_about);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_controllerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_controllerActionPerformed
        // TODO add your handling code here:
        if(controlador.listo){
            impresion imp = new impresion();
            mostrarVentanasInternas(imp, "CONTROLADOR DE IMPRESORA");
            controlador.setImpresora(imp) ;
        }
           
        else
            JOptionPane.showMessageDialog(this, "Aun no se han cargado las configuraciones iniciales!","ERROR",0);
       
    }//GEN-LAST:event_menu_controllerActionPerformed

    private void menu_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_userActionPerformed
        // TODO add your handling code here:
         mostrarVentanasInternas(new usuarios(), "Gestion de Usuarios");
    }//GEN-LAST:event_menu_userActionPerformed

    private void menu_acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_acercaActionPerformed
        // TODO add your handling code here:
        mostrarVentanasInternas(new about(), "Acerca de ");
    }//GEN-LAST:event_menu_acercaActionPerformed

    private void menu_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menu_salirActionPerformed

    private void menu_confActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_confActionPerformed
        // TODO add your handling code here:
         mostrarVentanasInternas(new Archivo(), "Aperturar Turno");
    }//GEN-LAST:event_menu_confActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        login lg = new login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenu menu_about;
    private javax.swing.JMenuItem menu_acerca;
    private javax.swing.JMenu menu_administrador;
    private javax.swing.JMenu menu_archivo;
    private javax.swing.JMenuItem menu_conf;
    private javax.swing.JMenuItem menu_controller;
    private javax.swing.JMenuItem menu_impresiones;
    private javax.swing.JMenuItem menu_salir;
    private javax.swing.JMenuItem menu_user;
    private javax.swing.JMenu menu_usuario;
    // End of variables declaration//GEN-END:variables
}
